# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Compile & Push

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: git pull --recursive-submodules=yes
    - run: yarn
    - run: TCGDEX_COMPILER_LANG=en yarn start
    - run: TCGDEX_COMPILER_LANG=fr yarn start
    - run: cd dist && git commit -m "Updated Database"
    - run: git push --recursive-submodules=on-demand
    - run: yarn upload
