# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Compile & Push

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile & Upload
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: git pull --recurse-submodules=yes
    - run: yarn db:compile
    - run: TCGDEX_COMPILER_LANG=en yarn start
    - run: TCGDEX_COMPILER_LANG=fr yarn start
    - run: yarn upload
    - run: git config --local user.email "bot@tcgdex.net"
    - run: git config --local user.name "TCGdex [bot]"
    - run: cd dist && git commit -m "Updated Database" -a && cd ../
      env:
        UPLOAD_REMOTE: ${{ secrets.UPLOAD_REMOTE }}
        UPLOAD_DIST: ${{ secrets.UPLOAD_DIST }}
        UPLOAD_USERNAME: ${{ secrets.UPLOAD_USERNAME }}
        UPLOAD_PASSWORD: ${{ secrets.UPLOAD_PASSWORD }}
    - name: Push changes
    - uses: ad-m/github-push-action@master
    - with:
        github_token: ${{ secrets.UPLOAD_TOKEN }}
        directory: './dist'
